### ISSUE TITLE
Skyper test suite does not pass

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#21]
Skyper test suite (described in README.md) does not pass. 

The error message is:

```
c:\PolyjuiceProjects\Polyjuice\Skyper>npm test

> skyper@0.0.0 test c:\PolyjuiceProjects\Polyjuice\Skyper
> mocha



  Skyper app
    √ Get cookie
    √ Verify cookie
    √ Click on add new friend
    √ Set first name
    √ Set last name
    √ Set skype name
    1) Save skype friend


  6 passing (51ms)
  1 failing

  1) Skyper app Save skype friend:
     Error: expected body 'System.NullReferenceException: Object reference not set
 to an instance of an object.\r\n   at Starcounter.Json.op_Implicit(Response r) in
 c:\\TeamCity\\TeamCity8\\buildAgent\\work\\sc-2.0.3103.3\\Level1\\src\\Starcounte
r.XSON\\Class Json\\Json.IResource.cs:line 64\r\n   at SkyperFriendsList.RefreshFr
iends() in c:\\PolyjuiceProjects\\Polyjuice\\Skyper\\Server\\SkyperFriendsList.jso
n.cs:line 10\r\n   at SkyperFriendsList.<Handle>b__7() in c:\\PolyjuiceProjects\\P
olyjuice\\Skyper\\Server\\SkyperFriendsList.json.cs:line 33\r\n   at SkyperEditPag
e.Handle(Save input) in c:\\PolyjuiceProjects\\Polyjuice\\Skyper\\Server\\SkyperEd
itPage.json.cs:line 14\r\n   at SkyperEditPage.JsonByExample.Schema.<.ctor>b__16(J
son pup, Input`1 input) in c:\\PolyjuiceProjects\\Polyjuice\\Skyper\\obj\\x64\\Deb
ug\\Server\\SkyperEditPage.json.g.cs:line 0\r\n   at Starcounter.Templates.Propert
y`1.ProcessInput(Json parent, T value) in c:\\TeamCity\\TeamCity8\\buildAgent\\wor
k\\sc-2.0.3103.3\\Level1\\src\\Starcounter.XSON\\Templates\\Foundation\\Property.c
s:line 230\r\n   at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TLong pro
perty, Json parent, IntPtr valuePtr, Int32 valueSize) in c:\\TeamCity\\TeamCity8\\
buildAgent\\work\\sc-2.0.3103.3\\Level1\\src\\Starcounter.XSON\\Sessions\\JSON-Pat
ch\\DefaultPatchHandler.cs:line 88\r\n   at Starcounter.Internal.TransactionManage
r.Scope(TransactionHandle handle, Action action) in c:\\TeamCity\\TeamCity8\\build
Agent\\work\\sc-2.0.3103.3\\Level1\\src\\Starcounter\\TransactionManager.cs:line 4
49\r\n   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action
) in c:\\TeamCity\\TeamCity8\\buildAgent\\work\\sc-2.0.3103.3\\Level1\\src\\Starco
unter.XSON\\Class Json\\JsonExtension.cs:line 19\r\n   at Starcounter.XSON.JsonPat
ch.EvaluatePatches(Session session, IntPtr patchArrayPtr, Int32 patchArraySize) in
 c:\\TeamCity\\TeamCity8\\buildAgent\\work\\sc-2.0.3103.3\\Level1\\src\\Starcounte
r.XSON\\Sessions\\JSON-Patch\\JsonPatch.cs:line 585\r\n   at Starcounter.Internal.
PuppetRestHandler.<RegisterJsonPatchHandlers>b__3(Session session, Request request
) in c:\\TeamCity\\TeamCity8\\buildAgent\\work\\sc-2.0.3103.3\\Level1\\src\\Starco
unter.Apps.JsonPatch\\BuiltInRestHandlers\\PuppetRestHandler.cs:line 93\r\n   at l
ambda_method(Closure , Request , IntPtr , IntPtr )\r\n   at Starcounter.Rest.UserH
andlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr
parametersInfoOnStack, HandlerOptions handlerOptions) in c:\\TeamCity\\TeamCity8\\
buildAgent\\work\\sc-2.0.3103.3\\Level1\\src\\Starcounter.Rest\\UriHandlersManager
.cs:line 165\r\n   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcess
Response(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request
req, HandlerOptions handlerOptions) in c:\\TeamCity\\TeamCity8\\buildAgent\\work\\
sc-2.0.3103.3\\Level1\\src\\Starcounter.Apps.JsonPatch\\AppRestServer.cs:line 96\r
\n   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req)
in c:\\TeamCity\\TeamCity8\\buildAgent\\work\\sc-2.0.3103.3\\Level1\\src\\Starcoun
ter.Apps.JsonPatch\\AppsBootstrapper.cs:line 276\r\nHResult=-2147467261\r\n\r\nMor
e information about this error may be available in the server error log.' to match
 /"path":"\/_ver#c[$]","value":5/
      at error (c:\PolyjuiceProjects\Polyjuice\Skyper\node_modules\supertest\lib\t
est.js:235:13)
      at Test.assert (c:\PolyjuiceProjects\Polyjuice\Skyper\node_modules\supertest
\lib\test.js:177:23)
      at assert (c:\PolyjuiceProjects\Polyjuice\Skyper\node_modules\supertest\lib\
test.js:132:12)
      at c:\PolyjuiceProjects\Polyjuice\Skyper\node_modules\supertest\lib\test.js:
129:5
      at Test.Request.callback (c:\PolyjuiceProjects\Polyjuice\Skyper\node_modules
\supertest\node_modules\superagent\lib\node\index.js:746:30)
      at Test.<anonymous> (c:\PolyjuiceProjects\Polyjuice\Skyper\node_modules\supe
rtest\node_modules\superagent\lib\node\index.js:135:10)
      at Test.emit (events.js:95:17)
      at IncomingMessage.<anonymous> (c:\PolyjuiceProjects\Polyjuice\Skyper\node_m
odules\supertest\node_modules\superagent\lib\node\index.js:938:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:943:16
      at process._tickCallback (node.js:419:13)



npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

The code for the test is here: https://github.com/Polyjuice/Skyper/blob/master/test/test.js

@chrhol could you please take a look? It seems like some problem between JSON and Db.Scope... I tried to investigate but could not get to work.

For some reason trying to do the test by repeating the same actions manually works OK. So maybe some problem caused by too fast execution of patches?

**Comment by chrhol** [comment]
I found and fixed a couple of bugs when registering transaction on session, but I don't think that makes any difference for this issue.

For this issue: If you run patches over websocket everything works fine. If you turn off websocket and use http you will get the same exception in both the test and when doing the steps manually.

The following row (in `SkyperFriendsList.RefreshFriends()`) is returning a response that is null. It looks like the partial handler is never called when originating from a patch.

```c#
SkyperFriendPage p = (SkyperFriendPage)X.GET("/Skyper/partials/contactinfo/" + contact.Somebody.Key);
```

There seems to be some mismatch in which appname is set. I can see that when the patch-handler is called the property `StarcounterEnvironment.AppName` is set to `"Launcher"` but it should be null. And in the Network-tab in the Administrator the handler is correctly registered with `NoApp` as application.

Not sure why the AppName is set to "Launcher", maybe it's an old value that is not reset since the thread can be reused. Maybe @alemoi have some idea.

I tested (as a hack) to just setting the appname to null in the handler and then it works fine, both manual steps and the test, but this does not feel like a good solution :)

**Comment by chrhol** [comment]
Or maybe the AppName should be set when evaluating the path in the patch? I guess this might be the correct way to do it.

**Comment by chrhol** [comment]
I implemented the change above and it seems to be working fine. I have some problems pushing and doing personal builds on the buildserver (same for everyone I guess). I will update this issue when I succeeded in pushing it to develop.

**Comment by chrhol** [comment]
Changes pushed now. The Skyper-test should succeed. I think it's disabled at the moment so maybe @parherman can enable it again.
